### PR TITLE
Run on the faster container testing

### PR DESCRIPTION
**Pull request by photodude**
This will speed up your testing as containers start faster

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
It looks like this change causes HHVM to stall during the test. I need to investigate if this is a HHVM or Travis CI issue before landing this.

**Comment by photodude** [comment]
Could be either. have you tried restarting the HHVM portion of the Travis test?
Note: Before this change you were testing against the EOL HHVM 3.6, with this change it's HHVM latest (3.18 currently) and will track with each release (i.e. will be 3.19 when 3.19 is released).

There is an option for testing against HHVM LST versions, if desired follow this guide. https://docs.travis-ci.com/user/languages/php#HHVM-versions

**Comment by photodude** [comment]
@NielsLeenheer I did a quick test of all HHVM LTS versions, looks like the stall out is happening on all versions >= 3.12
https://travis-ci.org/photodude/Parser/builds/205804532

**Comment by photodude** [comment]
Looks like hhvm-3.12 gives a clue
```php
Assertion failure: /tmp/tmp.DTRAphmwc7/hphp/runtime/vm/jit/translate-region.cpp:893: HPHP::jit::TranslateResult HPHP::jit::{anonymous}::mcGenRegion(HPHP::jit::IRGS&, const HPHP::jit::RegionDesc&, HPHP::jit::ProfSrcKeySet&): assertion `0' failed.
data block = cold
message: Attempted to emit 1 byte(s) into a 3401 byte DataBlock with 0 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAColdSize, Eval.JitAFrozenSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.
```

looks like it's a JIT issue with unit testing. I'm testing disabling the JIT as the JIT usually causes issues with Unit tests as the scripts are short lived.

**Comment by photodude** [comment]
Looks like it definitely is a unit test collision with the hhvm JIT. Following best advice for unit testing with hhvm disabling the JIT should be the correct resolution. (note: JIT enabled testing should happen at the user/acceptance testing level)

**Comment by NielsLeenheer** [comment]
Thanks for figuring out what the problem was, merging!

**Comment by photodude** [comment]
you are welcome

**Pull request merged**
